mydict1 = {'more important':2, 'substantially more important':3, 'equal importance':1}

from tkinter import *
from tkinter.messagebox import *

def first_interface():
    master = Tk()
    master.title('Getting Started')

    label1 = Label(master, text = 'what is factor 1:', relief = 'groove', width = 19)
    label2 = Label(master, text = 'what is factor 2:', relief = 'groove', width = 19)
    label3 = Label(master, text = 'what is factor 3:', relief = 'groove', width = 19)
    label4 = Label(master, text = 'what is factor 4:', relief = 'groove', width = 19)
    label5 = Label(master, text = 'what is factor 5:', relief = 'groove', width = 19)
    label6 = Label(master, text = 'what is factor 6:', relief = 'groove', width = 19)
    label7 = Label(master, text = 'factor 1 weight:', relief = 'groove', width = 19)
    label8 = Label(master, text = 'factor 2 weight:', relief = 'groove', width = 19)
    label9 = Label(master, text = 'factor 3 weight:', relief = 'groove', width = 19)
    label10 = Label(master, text = 'factor 4 weight:', relief = 'groove', width = 19)
    label11 = Label(master, text = 'factor 5 weight:', relief = 'groove', width = 19)
    label12 = Label(master, text = 'factor 6 weight:', relief = 'groove', width = 19)
    factor1 = Entry(master, relief = 'groove', width = 12)
    factor2 = Entry(master, relief = 'groove', width = 12)
    factor3 = Entry(master, relief = 'groove', width = 12)
    factor4 = Entry(master, relief = 'groove', width = 12)
    factor5 = Entry(master, relief = 'groove', width = 12)
    factor6 = Entry(master, relief = 'groove', width = 12)
    wfactor1 = Entry(master, relief = 'groove', width = 12)
    wfactor2 = Entry(master, relief = 'groove', width = 12)
    wfactor3 = Entry(master, relief = 'groove', width = 12)
    wfactor4 = Entry(master, relief = 'groove', width = 12)
    wfactor5 = Entry(master, relief = 'groove', width = 12)
    wfactor6 = Entry(master, relief = 'groove', width = 12)

    def start_second_interface():
        f1 = str(factor1.get())
        f2 = str(factor2.get())
        f3 = str(factor3.get())
        f4 = str(factor4.get())
        f5 = str(factor5.get())
        f6 = str(factor6.get())
        f7 = float(mydict1[wfactor1.get()])
        f8 = float(mydict1[wfactor2.get()])
        f9 = float(mydict1[wfactor3.get()])
        f10 = float(mydict1[wfactor4.get()])
        f11 = float(mydict1[wfactor5.get()])
        f12 = float(mydict1[wfactor6.get()])
        second_interface(f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12)

    button2 = Button(master, text = 'Go', relief = 'groove', width = 25, command=start_second_interface)

    label1.grid( row = 1, column = 1, padx = 10 )
    label2.grid( row = 2, column = 1, padx = 10 )
    label3.grid( row = 3, column = 1, padx = 10 )
    label4.grid( row = 4, column = 1, padx = 10 )
    label5.grid( row = 5, column = 1, padx = 10 )
    label6.grid( row = 6, column = 1, padx = 10 )
    label7.grid( row = 7, column = 1, padx = 10 )
    label8.grid( row = 8, column = 1, padx = 10 )
    label9.grid( row = 9, column = 1, padx = 10 )
    label10.grid( row = 10, column = 1, padx = 10 )
    label11.grid( row = 11, column = 1, padx = 10 )
    label12.grid( row = 12, column = 1, padx = 10 )
    factor1.grid( row = 1, column = 2, padx = 10 )
    factor2.grid( row = 2, column = 2, padx = 10 )
    factor3.grid( row = 3, column = 2, padx = 10 )
    factor4.grid( row = 4, column = 2, padx = 10 )
    factor5.grid( row = 5, column = 2, padx = 10 )
    factor6.grid( row = 6, column = 2, padx = 10 )
    wfactor1.grid( row = 7, column = 2, padx = 10 )
    wfactor2.grid( row = 8, column = 2, padx = 10 )
    wfactor3.grid( row = 9, column = 2, padx = 10 )
    wfactor4.grid( row = 10, column = 2, padx = 10 )
    wfactor5.grid( row = 11, column = 2, padx = 10 )
    wfactor6.grid( row = 12, column = 2, padx = 10 )
    button2.grid( row = 14, column = 1, columnspan = 2)


def second_interface(factor1, factor2, factor3, factor4, factor5, factor6, f7, f8, f9, f10, f11, f12):

    mydict = {'good':0.75, 'acceptable':0.5, 'outstanding': 1, 'unacceptable': 0, 'marginal': .25}

    master = Toplevel()
    label1 = Label(master, text = 'Proposal', relief = 'groove', width = 19)
    label2 = Label(master, text = factor1, relief = 'groove', width = 19)
    label3 = Label(master, text = factor2, relief = 'groove', width = 19)
    label4 = Label(master, text = factor3, relief = 'groove', width = 19)
    label5 = Label(master, text = factor4, relief = 'groove', width = 19)
    label6 = Label(master, text = factor5, relief = 'groove', width = 19)
    label7 = Label(master, text = factor6, relief = 'groove', width = 19)
    label8 = Label(master, text = 'A', relief = 'groove', width = 12)
    label9 = Label(master, text = 'B', relief = 'groove', width = 12)
    label10 = Label(master, text = 'C', relief = 'groove', width = 12)
    label11 = Label(master, text = 'Proposal Score', relief = 'groove', width = 19)
    entry1 = Entry(master, relief = 'groove', width = 12)
    entry2 = Entry(master, relief = 'groove', width = 12)
    entry3 = Entry(master, relief = 'groove', width = 12)
    entry4 = Entry(master, relief = 'groove', width = 12)
    entry5 = Entry(master, relief = 'groove', width = 12)
    entry6 = Entry(master, relief = 'groove', width = 12)
    entry7 = Entry(master, relief = 'groove', width = 12)
    entry8 = Entry(master, relief = 'groove', width = 12)
    entry9 = Entry(master, relief = 'groove', width = 12)
    entry10 = Entry(master, relief = 'groove', width = 12)
    entry11 = Entry(master, relief = 'groove', width = 12)
    entry12 = Entry(master, relief = 'groove', width = 12)
    entry13 = Entry(master, relief = 'groove', width = 12)
    entry14 = Entry(master, relief = 'groove', width = 12)
    entry15 = Entry(master, relief = 'groove', width = 12)
    entry16 = Entry(master, relief = 'groove', width = 12)
    entry17 = Entry(master, relief = 'groove', width = 12)
    entry18 = Entry(master, relief = 'groove', width = 12)
    blank1 = Entry(master, relief = 'groove', width = 12)
    blank2 = Entry(master, relief = 'groove', width = 12)
    blank3 = Entry(master, relief = 'groove', width = 12)

    def show_answer():
        npv1 = 1
        npv2 = .95
        npv3 = .2
        b = float(f7) + float(f8) + float(f9) + float(f10) + float(f11) + float(f12) 
        Ans1 =  float((npv1)**f7) * float(mydict[entry2.get()] ** f8) * float(mydict[entry3.get()] **f9) * float(mydict[entry4.get()] ** f10) * float(mydict[entry5.get()] ** f11) * float(mydict[entry6.get()] ** f12)
        Ansr1 = Ans1 ** b
        blank1.insert(0, Ansr1)
        Ans2 =  float(npv2 ** f7) * float(mydict[entry8.get()] ** f8) * float(mydict[entry9.get()] **f9) * float(mydict[entry10.get()] ** f10) * float(mydict[entry11.get()] ** f11) * float(mydict[entry12.get()] ** f12)
        Ansr2 = Ans2 ** b
        blank2.insert(0, Ansr2)
        Ans3 =  float(npv3 ** f7) * float(mydict[entry14.get()] ** f8) * float(mydict[entry15.get()] **f9) * float(mydict[entry16.get()] ** 10) * float(mydict[entry17.get()] ** f11) * float(mydict[entry18.get()] ** f12)
        Ansr3 = Ans3 ** b
        blank3.insert(0, Ansr3)
 
    button1 = Button(master, text = 'Calculate Proposal Scores', relief = 'groove', width = 25, command =show_answer)
 
    label1.grid( row = 1, column = 1, padx = 10 )
    label2.grid( row = 1, column = 2, padx = 10 )
    label3.grid( row = 1, column = 3, padx = 10 )
    label4.grid( row = 1, column = 4, padx = 10 )
    label5.grid( row = 1, column = 5, padx = 10 )
    label6.grid( row = 1, column = 6, padx = 10 )
    label7.grid( row = 1, column = 7, padx = 10 )
    label8.grid( row = 2, column = 1, padx = 10 )
    label9.grid( row = 3, column = 1, padx = 10 )
    label10.grid( row = 4, column = 1, padx = 10 )
    label11.grid( row = 1, column = 8, padx = 10 )
    entry1.grid( row = 2, column = 2, padx = 10 )
    entry2.grid( row = 2, column = 3, padx = 10 )
    entry3.grid( row = 2, column = 4, padx = 10 )
    entry4.grid( row = 2, column = 5, padx = 10 )
    entry5.grid( row = 2, column = 6, padx = 10 )
    entry6.grid( row = 2, column = 7, padx = 10 )
    entry7.grid( row = 3, column = 2, padx = 10 )
    entry8.grid( row = 3, column = 3, padx = 10 )
    entry9.grid( row = 3, column = 4, padx = 10 )
    entry10.grid( row = 3, column = 5, padx = 10 )
    entry11.grid( row = 3, column = 6, padx = 10 )
    entry12.grid( row = 3, column = 7, padx = 10 )
    entry13.grid( row = 4, column = 2, padx = 10 )
    entry14.grid( row = 4, column = 3, padx = 10 )
    entry15.grid( row = 4, column = 4, padx = 10 )
    entry16.grid( row = 4, column = 5, padx = 10 )
    entry17.grid( row = 4, column = 6, padx = 10 )
    entry18.grid( row = 4, column = 7, padx = 10 )
    blank1.grid( row = 2, column = 8, padx = 10 )
    blank2.grid( row = 3, column = 8, padx = 10 )
    blank3.grid( row = 4, column = 8, padx = 10 )
    button1.grid( row = 6, column = 4, columnspan = 2)

    #Static Properties
    master.title('Proposal Score Calculator')

first_interface()
